package com.drc.server.entity;

public enum ErrorMessageType {

    REGISTRATION_FAILED,
    QUESTION_NOT_FOUND,
    USER_NOT_FOUND,
    GAME_NOT_FOUND,
    COMMAND_NOT_SUPPORTED,
    GAME_ERROR,
    MINIMUM_PLAYERS_NOT_REACHED,
    SET_CHEATER_ERROR,
    NO_NEXT_QUESTION,
    BALANCE_ACTION_NOT_ALLOWED,
    BALANCE_WRONG_USERNAME,
    BALANCE_WRONG_VALUE



}
