package com.drc.server.entity;

public enum ResponseType {
    OK,
    SET_CHEATER,
    GAME_STARTED,
    NEXT_QUESTION,
    BALANCE_ACTION_OK,
    USER_CONNECTED,
    USER_DISCONNECTED,
    CLEAN_SERVER,
    PLAYER_KICKED,
    CHEATER_DRAWED,
    PROCESSED_CORRECT_ANSWER,
    END_ROUND_OK,
    SHOOT_PLAYER,
    ARE_YOU_CHEATER,
    GAME_END
}
